using BrewCode.BrewGuide;
using BrewComp.Identity;
using System.ComponentModel.DataAnnotations.Schema;

namespace BrewComp.Data;

public class CompetitionEntry
{
    [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
    public Guid Id { get; set; }
    public Competition Competition { get; set; } = null!;
    /// <summary>
    /// This Property is for the Competition Specific Entry ID, not to be confused
    /// with the overal GUID Id of the Entry. This will be generated by the software
    /// when an entry is registered for a Competition.
    /// </summary>
    public uint EntryId { get; set; }
    public string Name { get; set; } = string.Empty;
    public BrewCompUser Brewer { get; set; } = null!;
    public string? CoBrewer { get; set; } = null!;
    public IStyle Style { get; set; } = null!;
    public string? BrewersSpecs { get; set; }
    public string? Allergens { get; set; }
    public float? CompositeScore { get; set; }
    public bool Paid { get; set; } = false;

}
